spring:
  application:
    name: acma-registry-service
    version: 1.0.0

server:
  port: ${DISCOVERY_PORT:8761}

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
