spring:
  application:
    name: acma-usermgmt-service
server:
  port: ${SERVER_PORT:5051}

acma:
  iam:
    usersApi: ${PROTOCOL:http}://${IAM_USERS_API_HOST:am.acma.com}:${IAM_USERS_API_PORT:8081}/admin/realms/${IAM_REALM:acma}/users/
    groupsApi: ${PROTOCOL:http}://${IAM_USERS_API_HOST:am.acma.com}:${IAM_USERS_API_PORT:8081}/admin/realms/${IAM_REALM:acma}/groups/
    groups:
      property-owners: ${PROP_OWNERS_GROUP_ID:d8246eb5-4361-4ef4-9a8b-733cff85ac34}
      brokers: ${BROKERS_GROUP_ID:54be4bfb-ef71-4df5-b61d-4de6756dc4f0}
      agents: ${AGENTS_GROUP_ID:52cbf801-4214-47cb-a747-b2c3eca8e740}