spring:
  application:
    name: acma-authn-authz-service
    version: 1.0.0

  data:
    redis:
      host: ${ACMA_CACHE_HOST:localhost}
      port: ${ACMA_CACHE_PORT:6379}
      username: username
      password: password
  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: ott-insurer
            client-secret: vIfmtfpOF7ayb3g2m6rrL9Rp7G6iuWsE
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/"
            scope:
             - openid
        provider:
          keycloak:
            issuer-uri: http://am.acma.com:8081/realms/acma
            token-uri: http://am.acma.com:8081/realms/acma/protocol/openid-connect/token
server:
  port: ${APP_PORT:5052}
eureka:
  client:
    service-url:
       default-zone: http://${ACMA_REGISTRY_HOST:localhost}:${ACMA_REGISTRY_PORT:8761}/eureka/
  instance:
    #prefer-ip-address: true
    hostname: ${ACMA_AUTHNZ_REGISTRY_HOST:localhost}

management:
  endpoints:
    web:
      exposure:
        include: "*"



